"""empty message

Revision ID: 0c4cedfe6bee
Revises: d639b3b3b56d
Create Date: 2023-12-11 13:10:12.901458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4cedfe6bee'
down_revision = 'd639b3b3b56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_club_books_book_id_books', type_='foreignkey')
        batch_op.drop_constraint('fk_club_books_club_id_bookclubs', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_club_books_book_id_books'), 'books', ['book_id'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(batch_op.f('fk_club_books_club_id_bookclubs'), 'bookclubs', ['club_id'], ['id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_club_books_club_id_bookclubs'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_club_books_book_id_books'), type_='foreignkey')
        batch_op.create_foreign_key('fk_club_books_club_id_bookclubs', 'bookclubs', ['club_id'], ['id'])
        batch_op.create_foreign_key('fk_club_books_book_id_books', 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###
