"""recreate books and club books

Revision ID: 4bb8426b5460
Revises: 7de6e1a83179
Create Date: 2023-12-16 22:47:41.834629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb8426b5460'
down_revision = '7de6e1a83179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['bookclubs.id'], name=op.f('fk_books_club_id_bookclubs')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('club_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_club_books_book_id_books'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['club_id'], ['bookclubs.id'], name=op.f('fk_club_books_club_id_bookclubs'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_books')
    op.drop_table('books')
    # ### end Alembic commands ###
