"""remove many to many to debug

Revision ID: 5c0feab2fa85
Revises: fabdb0f78bc8
Create Date: 2023-12-16 18:47:38.432561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0feab2fa85'
down_revision = 'fabdb0f78bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_books')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_club_id_bookclubs', type_='foreignkey')
        batch_op.drop_column('club_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_books_club_id_bookclubs', 'bookclubs', ['club_id'], ['id'])

    op.create_table('club_books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.VARCHAR(), nullable=True),
    sa.Column('club_id', sa.INTEGER(), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='fk_club_books_book_id_books', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['club_id'], ['bookclubs.id'], name='fk_club_books_club_id_bookclubs', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
