"""empty message

Revision ID: 7cdc579c6bda
Revises: 0c4cedfe6bee
Create Date: 2023-12-11 19:10:35.877247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cdc579c6bda'
down_revision = '0c4cedfe6bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookclubs')
    op.drop_table('posts')
    op.drop_table('club_books')
    op.drop_table('books')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_bookclub_id_bookclubs', type_='foreignkey')
        batch_op.drop_column('bookclub_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookclub_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_bookclub_id_bookclubs', 'bookclubs', ['bookclub_id'], ['id'])

    op.create_table('books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('cover', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('club_books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('club_id', sa.INTEGER(), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='fk_club_books_book_id_books', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['club_id'], ['bookclubs.id'], name='fk_club_books_club_id_bookclubs', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='fk_posts_book_id_books'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_posts_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookclubs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('club_name', sa.VARCHAR(), nullable=True),
    sa.Column('picture', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
